/*
Humanloop API

The Humanloop API allows you to interact with Humanloop from your product or service.

You can do this through HTTP requests from any language or via our official Python or TypeScript SDK.

To install the official [Python SDK](https://pypi.org/project/humanloop/), run the following command:

```bash
pip install humanloop
```

To install the official [TypeScript SDK](https://www.npmjs.com/package/humanloop), run the following command:

```bash
npm i humanloop
```

---

Guides and further details about key concepts can be found in [our docs](https://docs.humanloop.com/).

The version of the OpenAPI document: 4.0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ChatRole } from './chat-role';
import { ContentProperty } from './content-property';
import { ToolCall } from './tool-call';
import { ToolCallProperty1 } from './tool-call-property1';

/**
 * 
 * @export
 * @interface ChatMessageWithToolCall
 */
export interface ChatMessageWithToolCall {
    /**
     * 
     * @type {ContentProperty}
     * @memberof ChatMessageWithToolCall
     */
    'content'?: ContentProperty | null;
    /**
     * Optional name of the message author.
     * @type {string}
     * @memberof ChatMessageWithToolCall
     */
    'name'?: string | null;
    /**
     * Tool call that this message is responding to.
     * @type {string}
     * @memberof ChatMessageWithToolCall
     */
    'tool_call_id'?: string | null;
    /**
     * Role of the message author.
     * @type {ChatRole}
     * @memberof ChatMessageWithToolCall
     */
    'role': ChatRole;
    /**
     * A list of tool calls requested by the assistant.
     * @type {Array<ToolCall>}
     * @memberof ChatMessageWithToolCall
     */
    'tool_calls'?: Array<ToolCall> | null;
    /**
     * 
     * @type {ToolCallProperty1}
     * @memberof ChatMessageWithToolCall
     * @deprecated
     */
    'tool_call'?: ToolCallProperty1 | null;
}

