/* tslint:disable */
/* eslint-disable */
/**
 * Humanloop API
 * The Humanloop API allows you to interact with Humanloop from your product or service.  You can do this through HTTP requests from any language or via our official Python or TypeScript SDK.  To install the official [Python SDK](https://pypi.org/project/humanloop/), run the following command:  ```bash pip install humanloop ```  To install the official [TypeScript SDK](https://www.npmjs.com/package/humanloop), run the following command:  ```bash npm i humanloop ```  ---  Guides and further details about key concepts can be found in [our docs](https://docs.humanloop.com/).
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ChatMessage } from './chat-message';
// May contain unused imports in some cases
// @ts-ignore
import { ChatRole } from './chat-role';
// May contain unused imports in some cases
// @ts-ignore
import { Target } from './target';
// May contain unused imports in some cases
// @ts-ignore
import { ToolCallProperty } from './tool-call-property';

/**
 * 
 * @export
 * @interface CreateTestcaseRequest
 */
export interface CreateTestcaseRequest {
    /**
     * The inputs to the prompt template for this testcase.
     * @type {{ [key: string]: string; }}
     * @memberof CreateTestcaseRequest
     */
    'inputs'?: { [key: string]: string; };
    /**
     * The chat messages for this testcase.
     * @type {Array<ChatMessage>}
     * @memberof CreateTestcaseRequest
     */
    'messages'?: Array<ChatMessage>;
    /**
     * Object with criteria necessary to evaluate this testcase.
     * @type {{ [key: string]: Target; }}
     * @memberof CreateTestcaseRequest
     */
    'target'?: { [key: string]: Target; };
}

