/*
Humanloop API

The Humanloop API allows you to interact with Humanloop from your product or service.

You can do this through HTTP requests from any language or via our official Python or TypeScript SDK.

To install the official [Python SDK](https://pypi.org/project/humanloop/), run the following command:

```bash
pip install humanloop
```

To install the official [TypeScript SDK](https://www.npmjs.com/package/humanloop), run the following command:

```bash
npm i humanloop
```

---

Guides and further details about key concepts can be found in [our docs](https://docs.humanloop.com/).

The version of the OpenAPI document: 4.0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EvaluatorArgumentsType } from './evaluator-arguments-type';
import { EvaluatorReturnTypeEnum } from './evaluator-return-type-enum';
import { ModelConfigResponse } from './model-config-response';
import { UserResponse } from './user-response';

/**
 * 
 * @export
 * @interface EvaluatorConfigResponse
 */
export interface EvaluatorConfigResponse {
    /**
     * Description of config.
     * @type {string}
     * @memberof EvaluatorConfigResponse
     */
    'description'?: string;
    /**
     * String ID of config. Starts with `config_`.
     * @type {string}
     * @memberof EvaluatorConfigResponse
     */
    'id': string;
    /**
     * Other parameters that define the config.
     * @type {object}
     * @memberof EvaluatorConfigResponse
     */
    'other'?: object;
    /**
     * 
     * @type {string}
     * @memberof EvaluatorConfigResponse
     */
    'type': EvaluatorConfigResponseTypeEnum;
    /**
     * The user who created the config.
     * @type {UserResponse}
     * @memberof EvaluatorConfigResponse
     */
    'created_by'?: UserResponse;
    /**
     * Whether the config is committed or not.
     * @type {string}
     * @memberof EvaluatorConfigResponse
     */
    'status': string;
    /**
     * Name of config.
     * @type {string}
     * @memberof EvaluatorConfigResponse
     */
    'name': string;
    /**
     * Type of evaluator.
     * @type {string}
     * @memberof EvaluatorConfigResponse
     */
    'evaluator_type': string;
    /**
     * The model config defining the LLM evaluator.
     * @type {ModelConfigResponse}
     * @memberof EvaluatorConfigResponse
     */
    'model_config'?: ModelConfigResponse;
    /**
     * The code for the evaluator. This code will be executed in a sandboxed environment.
     * @type {string}
     * @memberof EvaluatorConfigResponse
     */
    'code'?: string;
    /**
     * Whether this evaluator is target-free or target-required.
     * @type {EvaluatorArgumentsType}
     * @memberof EvaluatorConfigResponse
     */
    'arguments_type'?: EvaluatorArgumentsType;
    /**
     * The type of the return value of the evaluator.
     * @type {EvaluatorReturnTypeEnum}
     * @memberof EvaluatorConfigResponse
     */
    'return_type'?: EvaluatorReturnTypeEnum;
}

type EvaluatorConfigResponseTypeEnum = 'evaluator'


