/*
Humanloop API

The Humanloop API allows you to interact with Humanloop from your product or service.

You can do this through HTTP requests from any language or via our official Python or TypeScript SDK.

To install the official [Python SDK](https://pypi.org/project/humanloop/), run the following command:

```bash
pip install humanloop
```

To install the official [TypeScript SDK](https://www.npmjs.com/package/humanloop), run the following command:

```bash
npm i humanloop
```

---

Guides and further details about key concepts can be found in [our docs](https://docs.humanloop.com/).

The version of the OpenAPI document: 4.0.1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FeedbackTypeProperty } from './feedback-type-property';
import { FeedbackValueProperty1 } from './feedback-value-property1';

/**
 * 
 * @export
 * @interface FeedbackRequest
 */
export interface FeedbackRequest {
    /**
     * 
     * @type {FeedbackTypeProperty}
     * @memberof FeedbackRequest
     */
    'type': FeedbackTypeProperty;
    /**
     * 
     * @type {FeedbackValueProperty1}
     * @memberof FeedbackRequest
     */
    'value'?: FeedbackValueProperty1;
    /**
     * ID to associate the feedback to a previously logged datapoint.
     * @type {string}
     * @memberof FeedbackRequest
     */
    'data_id'?: string;
    /**
     * A unique identifier to who provided the feedback.
     * @type {string}
     * @memberof FeedbackRequest
     */
    'user'?: string;
    /**
     * User defined timestamp for when the feedback was created. 
     * @type {string}
     * @memberof FeedbackRequest
     */
    'created_at'?: string;
    /**
     * If true, the value for this feedback is unset.
     * @type {boolean}
     * @memberof FeedbackRequest
     */
    'unset'?: boolean;
}

