/*
Humanloop API

The Humanloop API allows you to interact with Humanloop from your product or service.

You can do this through HTTP requests from any language or via our official Python or TypeScript SDK.

To install the official [Python SDK](https://pypi.org/project/humanloop/), run the following command:

```bash
pip install humanloop
```

To install the official [TypeScript SDK](https://www.npmjs.com/package/humanloop), run the following command:

```bash
npm i humanloop
```

---

Guides and further details about key concepts can be found in [our docs](https://docs.humanloop.com/).

The version of the OpenAPI document: 4.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { ChatMessage } from './chat-message';
import { ChatRole } from './chat-role';
import { CreateTestcaseByDatapointsRequest } from './create-testcase-by-datapoints-request';
import { CreateTestcaseRequest } from './create-testcase-request';
import { Target } from './target';
import { ToolCallProperty } from './tool-call-property';

/**
 * @type TestsetsCreateTestcaseRequest
 * @export
 */
export type TestsetsCreateTestcaseRequest = CreateTestcaseByDatapointsRequest | CreateTestcaseRequest | Array<CreateTestcaseRequest>;


